services:
  - type: web
    name: shaktisinh-portfolio
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
