# Generated by Django 5.2.17 on 2026-09-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('organization', models.CharField(max_length=120)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-issued_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=180)),
                ('period', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-period'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=120)),
                ('headline', models.CharField(default='Fresher Software Developer', max_length=180)),
                ('bio', models.TextField(default='I build clean, scalable and user-focused web applications with Python and Django.')),
                ('objective', models.TextField(default='Seeking an opportunity to contribute as a software developer while growing through meaningful product work.')),
                ('location', models.CharField(default='Open to remote and onsite opportunities', max_length=120)),
                ('education', models.CharField(default='Add your degree and institution', max_length=180)),
                ('availability', models.CharField(default='Open to opportunities', max_length=120)),
                ('email', models.EmailField(default='hello@example.com', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('features', models.TextField(help_text='One feature per line.')),
                ('technologies', models.CharField(help_text='Comma-separated technologies.', max_length=250)),
                ('challenges', models.TextField(blank=True)),
                ('learnings', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('Tools', 'Tools')], max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=70, help_text='Use an honest estimate from 1 to 100.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
